### ISSUE TITLE
Custom validator generate invalid output

### ISSUE THREAD

**Issue by exejutable** [epiphone/routing-controllers-openapi#91]
A custom decorator breaks the generation of the spec

```typescript
export function IsResourceExist(resourceManager: any, key?: string) {
  return function resourceExist(object: Object, propertyName: string) {
    registerDecorator({
      name: 'IsResourceExist',
      target: object.constructor,
      propertyName,
      validator: {
        async validate(value: any): Promise<boolean> {
          let exist = true;

          if (value) {
            let manager: find = Container.get(resourceManager);
           
            await manager.find(new Pagination({ [key || 'id']: value }));
          
          }

          return exist;
        },
      }
    });
  };
}

class Example {
  @IsNumber({}, { each: true })
  @IsArray()
  @JSONSchema({
    description: 'Payment gateways ID',
    example: [1, 2],
  })
  @IsResourceExist(PaymentGatewayManager)
  payment_gateways: number[]

}
```

this returns in the yaml 

```yaml

   Example :
      properties:
        payment_gateways:
          $ref: '#/components/schemas/Array'
          items:
            type: number
          type: array
          description: Payment gateways ID
          example:
            - 1
            - 2

```

If i remove the custom decorator, the documentation is generated as spected 

```yaml

   Example :
      properties:
        payment_gateways:
          items:
            type: number
          type: array
          description: Payment gateways ID
          example:
            - 1
            - 2

```
